name = "mtg-card-worker"
main = "src/worker.js"
compatibility_date = "2024-01-15"

# KV Namespaces
[[kv_namespaces]]
binding = "CARD_CACHE"
id = "your_kv_namespace_id_here"
preview_id = "your_preview_kv_namespace_id_here"

# Environment variables
[env.production.vars]
ALLOWED_ORIGIN = "https://your-domain.com"

# Routes
[[env.production.routes]]
pattern = "your-domain.com/api/cards/*"
zone_name = "your-domain.com"