// Comprehensive list of Magic: The Gathering strategic themes
// AI must choose only from these predefined categories (1000+ themes)

export const PREDEFINED_THEMES = [
  // Core Archetypes & Strategies
  "Aggro",
  "Control",
  "Midrange",
  "Combo",
  "Tempo",
  "Prison",
  "Stax",
  "Hatebears",
  "Burn",
  "Mill",
  "Voltron",
  "Group Slug",
  "Group Hug",
  "Pillow Fort",
  "Chaos",
  "Tax Effects",
  "Resource Denial",
  "Asymmetric Effects",
  "Linear Strategy",
  "Nonlinear Strategy",
  "All-In Strategy",
  "Backup Plan",
  "Plan B",
  "Flexible Gameplan",
  "Resilient Strategy",
  "Glass Cannon",
  "Consistent Strategy",
  "Explosive Potential",
  "Midrange Value",
  "Permission Control",
  "Tap-Out Control",
  "Draw-Go",
  "Reactive Control",
  "Proactive Control",
  "Lock Pieces",
  "Soft Lock",
  "Hard Lock",
  "Symmetrical Effects",
  "Asymmetrical Advantage",
  "Win-More",
  "Comeback Potential",
  "Late Game",
  "Early Game",
  "Mid Game",
  "Turn Order Matters",
  "Multiplayer Politics",
  "Kingmaker",
  "Threat Assessment",
  "Table Management",

  // Resource Management & Card Advantage
  "Card Advantage",
  "Card Disadvantage",
  "Virtual Card Advantage",
  "Tempo Advantage",
  "Mana Advantage",
  "Board Advantage",
  "Life Advantage",
  "Information Advantage",
  "Ramp",
  "Explosive Ramp",
  "Gradual Ramp",
  "Creature Ramp",
  "Artifact Ramp",
  "Spell Ramp",
  "Mana Dorks",
  "Mana Rocks",
  "Mana Doublers",
  "Mana Reduction",
  "Cost Reduction",
  "Free Spells",
  "Alternative Costs",
  "Convoke",
  "Delve",
  "Emerge",
  "Evoke",
  "Madness",
  "Cycling",
  "Kicker",
  "Multikicker",
  "Overload",
  "Suspend",
  "Split Cards",
  "Modal Spells",
  "Hybrid Mana",
  "Phyrexian Mana",
  "Colorless Matters",
  "Generic Mana",
  "Land Destruction",
  "Mana Denial",
  "Resource Destruction",
  "Hand Disruption",
  "Discard Synergy",
  "Hellbent",
  "No Max Hand Size",
  "Draw Engines",
  "Draw Sevens",
  "Wheel Effects",
  "Cantrips",
  "Card Selection",
  "Scry",
  "Surveil",
  "Explore",
  "Impulse Draw",
  "Exile Draw",
  "Top Deck Manipulation",
  "Bottom Deck Manipulation",
  "Shuffle Effects",
  "Tutoring",
  "Creature Tutors",
  "Spell Tutors",
  "Land Tutors",
  "Artifact Tutors",
  "Enchantment Tutors",
  "Planeswalker Tutors",
  "Library Manipulation",
  "Deck Thinning",
  "Card Velocity",
  "Selection Effects",
  "Resource Conversion",
  "Mana Fixing",
  "Color Fixing",
  "Multicolor Support",
  "Five Color",
  "Four Color",
  "Three Color",
  "Two Color",
  "Monocolored",
  "Devotion",
  "Chroma",

  // Creature Strategies & Synergies
  "Tribal",
  "Go-Wide",
  "Go-Tall",
  "Tokens",
  "Token Doublers",
  "Token Producers",
  "Sacrifice Outlets",
  "Aristocrats",
  "Death Triggers",
  "Sacrifice Synergy",
  "Sacrifice for Value",
  "Free Sacrifice",
  "Forced Sacrifice",
  "Reanimator",
  "Mass Reanimation",
  "Selective Reanimation",
  "Creature Cheating",
  "Show and Tell",
  "Sneak Attack",
  "Graveyard Value",
  "Graveyard Hate",
  "Graveyard Protection",
  "Big Creatures",
  "Fatties",
  "Eldrazi",
  "Dragons",
  "Demons",
  "Angels",
  "Leviathans",
  "Krakens",
  "Octopus",
  "Serpents",
  "Sea Monsters",
  "ETB Value",
  "ETB Triggers",
  "LTB Value",
  "Dies Triggers",
  "Blink/Flicker",
  "Exile and Return",
  "Temporary Exile",
  "Permanent Exile",
  "Flicker Loops",
  "Creature Toolbox",
  "Utility Creatures",
  "Silver Bullets",
  "Hatching",
  "Creature Tutors",
  "Creature Recursion",
  "Clone Effects",
  "Copy Creatures",
  "Polymorph Effects",
  "Mass Creature Effects",
  "Creature Transformation",
  "Creature Animation",
  "Living Weapons",
  "Equipment Creatures",
  "Artifact Creatures",
  "Enchantment Creatures",
  "Land Creatures",
  "Vehicle Crew",
  "Crew Synergy",
  "Pilot Matters",
  "Small Creatures",
  "Large Creatures",
  "Medium Creatures",
  "X/X Creatures",
  "Growing Creatures",
  "Shrinking Creatures",
  "Variable P/T",
  "High Toughness",
  "High Power",
  "Zero Power",
  "One Toughness",
  "Defender",
  "Walls",
  "Reach",
  "Flying",
  "Vigilance",
  "Haste",
  "Trample",
  "Lifelink",
  "Deathtouch",
  "First Strike",
  "Double Strike",
  "Menace",
  "Intimidate",
  "Fear",
  "Landwalk",
  "Islandwalk",
  "Swampwalk",
  "Mountainwalk",
  "Forestwalk",
  "Plainswalk",
  "Shadow",
  "Horsemanship",
  "Skulk",
  "Hexproof",
  "Shroud",
  "Protection",
  "Indestructible",
  "Regeneration",
  "Undying",
  "Persist",
  "Unearth",
  "Echo",
  "Cumulative Upkeep",
  "Upkeep Cost",
  "Maintenance Cost",

  // Combat & Damage
  "Combat Tricks",
  "Pump Spells",
  "Evasion",
  "Double Strike",
  "Trample",
  "Flying Matters",
  "Unblockable",
  "Direct Damage",
  "Lifegain",
  "Lifelink Matters",
  "Lifegain Matters",
  "Drain Strategy",
  "Life Total Matters",
  "Damage Redirection",
  "Combat Control",
  "Alpha Strike",
  "Pingers",
  "Deathtouch Matters",
  "First Strike Matters",
  "Vigilance Matters",

  // Spell-Based Strategies
  "Spellslinger",
  "Storm",
  "Cascade",
  "Cascade/Cheating",
  "Cost Reduction",
  "X-Spells",
  "Instant Speed",
  "Flash",
  "Counterspells",
  "Removal",
  "Board Wipes",
  "Spot Removal",
  "Copy Spells",
  "Spell Recursion",
  "Big Spells",
  "Ritual Effects",
  "Spell Velocity",
  "Spell Matters",
  "Magecraft",
  "Prowess",

  // Artifact Strategies
  "Artifacts Matter",
  "Equipment",
  "Equipment Voltron",
  "Artifact Ramp",
  "Artifact Combo",
  "Metalcraft",
  "Affinity",
  "Modular",
  "Artifact Tokens",
  // Enchantment Strategies & Synergies
  "Enchantments Matter",
  "Enchantment Count",
  "Enchantment Triggers",
  "Auras Strategy",
  "Aura Voltron",
  "Aura Ramp",
  "Aura Recursion",
  "Aura Tutors",
  "Totem Armor",
  "Bestow",
  "Enchant Land",
  "Enchant Creature",
  "Enchant Player",
  "Enchant Artifact",
  "Enchantress Strategy",
  "Enchantress Engines",
  "Draw on Enchantment",
  "Constellation",
  "Constellation Triggers",
  "Enchantment ETB",
  "Curse Strategy",
  "Curse Tribal",
  "Curse Politics",
  "Group Curse",
  "Targeted Curses",
  "Enchantment Removal",
  "Enchantment Destruction",
  "Enchantment Sacrifice",
  "Enchantment Recursion",
  "Enchantment Graveyard",
  "Saga Strategy",
  "Saga Synergy",
  "Chapter Abilities",
  "Saga Recursion",
  "Global Enchantments",
  "World Effects",
  "Permanent Effects",
  "Static Enchantments",
  "Triggered Enchantments",
  "Enchantment Tokens",
  "Token Enchantments",
  "Enchantment Creatures",
  "Nyx Strategy",
  "God Strategy",
  "Devotion Enchantments",

  // Planeswalker Strategies
  "Planeswalker Strategy",
  "Superfriends",
  "Planeswalker Protection",
  "Planeswalker Proliferate",
  "Loyalty Counters",
  "Loyalty Manipulation",
  "Planeswalker Tutors",
  "Planeswalker Recursion",
  "Multiple Planeswalkers",
  "Planeswalker Tribal",
  "Spark Double",
  "Copy Planeswalker",
  "Planeswalker Tokens",
  "Planeswalker Creatures",
  "Compleated",
  "Planeswalker Removal",
  "Planeswalker Damage",
  "Ultimate Abilities",
  "Plus Abilities",
  "Minus Abilities",
  "Static Loyalty",
  "Starting Loyalty",

  // Land Strategies & Mechanics
  "Landfall",
  "Lands Matter",
  "Land Ramp",
  "Land Sacrifice",
  "Land Destruction",
  "Mass Land Destruction",
  "Targeted Land Destruction",
  "Utility Lands",
  "Creature Lands",
  "Man Lands",
  "Fetch Lands",
  "Shock Lands",
  "Dual Lands",
  "Triple Lands",
  "Bounce Lands",
  "Sac Lands",
  "Tap Lands",
  "Fast Lands",
  "Filter Lands",
  "Pain Lands",
  "Check Lands",
  "Battle Lands",
  "Tango Lands",
  "Bicycle Lands",
  "Cycling Lands",
  "Multicolor Fixing",
  "Five Color Mana",
  "WUBRG",
  "Rainbow Mana",
  "Chromatic Mana",
  "Land Animation",
  "Awaken",
  "Land Tutors",
  "Rampant Growth",
  "Explosive Vegetation",
  "Kodama's Reach",
  "Cultivate",
  "Harrow",
  "Basic Lands Matter",
  "Basic Land Types",
  "Plains",
  "Islands",
  "Swamps",
  "Mountains",
  "Forests",
  "Wastes",
  "Snow Lands",
  "Snow Matters",
  "Nonbasic Hate",
  "Blood Moon",
  "Back to Basics",
  "Price of Progress",
  "Domain",
  "Converge",
  "Sunburst",
  "Gate Synergy",
  "Maze's End",
  "Desert Synergy",
  "Cycling Lands",
  "Enters Tapped",
  "Enters Untapped",
  "Conditional Untapped",
  "Sacrifice Land",
  "Bounce Land",
  "Comes Into Play",
  "Land ETB",
  "Land Types Matter",
  "Changeling Lands",
  "Tribal Lands",
  "Legendary Lands",
  "Artifact Lands",
  "Enchantment Lands",
  "Creature Lands",
  "Planeswalker Lands",

  // Graveyard Strategies & Mechanics
  "Graveyard Recursion",
  "Graveyard Value",
  "Graveyard Synergy",
  "Graveyard as Resource",
  "Graveyard Protection",
  "Graveyard Hate",
  "Self-Mill",
  "Mill Others",
  "Mill Everyone",
  "Library Destruction",
  "Forced Mill",
  "Optional Mill",
  "Dredge",
  "Delve",
  "Flashback",
  "Jump-Start",
  "Threshold",
  "Delirium",
  "Escape",
  "Embalm",
  "Eternalize",
  "Unearth",
  "Retrace",
  "Disturb",
  "Aftermath",
  "Split Cards",
  "Fuse",
  "Fill Graveyard",
  "Empty Graveyard",
  "Graveyard Order",
  "Graveyard Shuffle",
  "Reanimation",
  "Mass Reanimation",
  "Selective Reanimation",
  "Recursive Threats",
  "Graveyard Loops",
  "Flashback Loops",
  "Dredge Loops",
  "Living Death",
  "Reanimate",
  "Animate Dead",
  "Necromancy",
  "Dance of the Dead",
  "Exhume",
  "Resurrection",
  "Return to Hand",
  "Return to Battlefield",
  "Return to Library",
  "Exile from Graveyard",
  "Graveyard Exile",
  "Rest in Peace",
  "Tormod's Crypt",
  "Relic of Progenitus",
  "Scavenging Ooze",
  "Deathrite Shaman",
  "Graveyard Tutorage",
  "Entomb",
  "Buried Alive",
  "Survival of the Fittest",
  "Intuition",
  "Gifts Ungiven",

  // Counter & Token Strategies
  "+1/+1 Counters",
  "-1/-1 Counters",
  "Counter Manipulation",
  "Counter Removal",
  "Counter Addition",
  "Counter Doubling",
  "Counter Moving",
  "Proliferate",
  "Proliferate Triggers",
  "Planeswalker Support",
  "Loyalty Manipulation",
  "Loyalty Counters",
  "Planeswalker Protection",
  "Superfriends",
  "Energy",
  "Energy Generation",
  "Energy Spending",
  "Energy Storage",
  "Experience Counters",
  "Experience Matters",
  "Charge Counters",
  "Storage Counters",
  "Time Counters",
  "Suspend",
  "Vanishing",
  "Fading",
  "Echo",
  "Poison Counters",
  "Infect",
  "Poisonous",
  "Toxic",
  "Wither",
  "Undying",
  "Persist",
  "Evolve",
  "Adapt",
  "Monstrosity",
  "Level Up",
  "Levelers",
  "Quest Counters",
  "Verse Counters",
  "Age Counters",
  "Arrowhead Counters",
  "Blaze Counters",
  "Blood Counters",
  "Bounty Counters",
  "Bribery Counters",
  "Currency Counters",
  "Death Counters",
  "Doom Counters",
  "Dream Counters",
  "Elixir Counters",
  "Fate Counters",
  "Feather Counters",
  "Flood Counters",
  "Fuse Counters",
  "Glyph Counters",
  "Gold Counters",
  "Growth Counters",
  "Hatchling Counters",
  "Healing Counters",
  "Hoofprint Counters",
  "Hunger Counters",
  "Ice Counters",
  "Infection Counters",
  "Intervention Counters",
  "Javelin Counters",
  "Ki Counters",
  "Loyalty Counters",
  "Luck Counters",
  "Matrix Counters",
  "Muster Counters",
  "Net Counters",
  "Omen Counters",
  "Ore Counters",
  "Page Counters",
  "Pain Counters",
  "Petal Counters",
  "Phylactery Counters",
  "Pin Counters",
  "Plague Counters",
  "Polyp Counters",
  "Pressure Counters",
  "Pupa Counters",
  "Rust Counters",
  "Scream Counters",
  "Shell Counters",
  "Shield Counters",
  "Sleep Counters",
  "Slime Counters",
  "Spore Counters",
  "Study Counters",
  "Theft Counters",
  "Tide Counters",
  "Tower Counters",
  "Training Counters",
  "Trap Counters",
  "Treasure Counters",
  "Unity Counters",
  "Velocity Counters",
  "Vitality Counters",
  "Wage Counters",
  "Wind Counters",
  "Wish Counters",

  // Timing & Phase Strategies
  "Timing Matters",
  "Phase Manipulation",
  "Turn Structure",
  "Upkeep",
  "Upkeep Triggers",
  "Draw Step",
  "Main Phase",
  "Pre-Combat Main",
  "Post-Combat Main",
  "Beginning of Combat",
  "Declare Attackers",
  "Declare Blockers",
  "Combat Damage",
  "End of Combat",
  "End Step",
  "End Step Matters",
  "Cleanup Step",
  "Extra Turns",
  "Time Walk",
  "Extra Phases",
  "Extra Combat",
  "Multiple Combats",
  "Skip Turns",
  "Skip Phases",
  "Skip Steps",
  "Instant Speed",
  "Instant Speed Value",
  "Flash",
  "Split Second",
  "Can't Be Countered",
  "Stack Interaction",
  "Triggered Abilities",
  "Triggered Control",
  "Trigger Stacking",
  "Activated Abilities",
  "Activated Control",
  "Mana Abilities",
  "Static Abilities",
  "Replacement Effects",
  "Prevention Effects",
  "Continuous Effects",
  "Temporary Effects",
  "Until End of Turn",
  "This Turn",
  "Next Turn",
  "Each Turn",
  "Each Upkeep",
  "Each Combat",
  "Each End Step",
  "Once Per Turn",
  "Twice Per Turn",
  "During Combat",
  "During Main Phase",
  "During Upkeep",
  "At Beginning",
  "At End",
  "When Cast",
  "When Dies",
  "When Enters",
  "When Leaves",
  "When Attacks",
  "When Blocks",
  "When Tapped",
  "When Untapped",
  "Enters Tapped",
  "Enters Untapped",
  "Stays Tapped",
  "Doesn't Untap",
  "Tap Synergy",
  "Untap Synergy",
  "Vigilance Matters",

  // Protection & Resilience
  "Protection",
  "Protection from Colors",
  "Protection from Types",
  "Protection from Everything",
  "Hexproof",
  "Shroud",
  "Hexproof from Color",
  "Ward",
  "Ward Costs",
  "Spell Protection",
  "Ability Protection",
  "Indestructible",
  "Regeneration",
  "Totem Armor",
  "Shield Counters",
  "Damage Prevention",
  "Damage Redirection",
  "Damage Reduction",
  "Damage Immunity",
  "Combat Damage",
  "Noncombat Damage",
  "Prevent All Damage",
  "Absorb Damage",
  "Bounce Effects",
  "Return to Hand",
  "Return to Library",
  "Return to Battlefield",
  "Phasing",
  "Phase Out",
  "Phase In",
  "Blink Protection",
  "Flicker Protection",
  "Sacrifice Protection",
  "Exile Protection",
  "Graveyard Protection",
  "Hand Protection",
  "Library Protection",
  "Battlefield Protection",
  "Permanent Protection",
  "Spell Protection",
  "Counterspell Protection",
  "Removal Protection",
  "Wrath Protection",
  "Board Wipe Protection",
  "Spot Removal Protection",
  "Mass Removal Protection",
  "Targeted Protection",
  "Untargeted Protection",
  "Cannot Be Targeted",
  "Cannot Be Blocked",
  "Cannot Be Countered",
  "Cannot Be Destroyed",
  "Cannot Be Sacrificed",
  "Cannot Be Exiled",
  "Cannot Attack",
  "Cannot Block",
  "Cannot Activate",
  "Cannot Be Equipped",
  "Cannot Be Enchanted",
  "Spell Immunity",
  "Ability Immunity",
  "Color Immunity",
  "Type Immunity",

  // Specific Mechanics (A-M)
  "Cycling",
  "Madness",
  "Morph",
  "Suspend",
  "Kicker",
  "Overload",
  "Convoke",
  "Emerge",
  "Mutate",
  "Adventure",
  "Foretell",
  "Miracle",
  "Buyback",
  "Echo",
  "Entwine",
  "Fading",
  "Vanishing",
  "Forecast",
  "Graft",
  "Haunt",
  "Hideaway",
  "Kinship",
  "Ninjutsu",
  "Offering",
  "Reinforce",
  "Ripple",
  "Splice",
  "Transmute",
  "Amplify",
  "Bloodthirst",
  "Clash",
  "Conspire",
  "Devour",
  "Exalted",
  "Landfall",
  "Level Up",
  "Multikicker",

  // Specific Mechanics (N-Z)
  "Annihilator",
  "Battle Cry",
  "Living Weapon",
  "Phyrexian Mana",
  "Soulbond",
  "Undying",
  "Cipher",
  "Evolve",
  "Extort",
  "Fuse",
  "Scavenge",
  "Unleash",
  "Bestow",
  "Heroic",
  "Inspired",
  "Strive",
  "Tribute",
  "Dash",
  "Exploit",
  "Formidable",
  "Megamorph",
  "Prowess",
  "Rebound",
  "Surge",
  "Awaken",
  "Ingest",
  "Devoid",
  "Colorless Matters",
  "Crew",
  "Fabricate",
  "Partner",
  "Improvise",
  "Revolt",
  "Aftermath",
  "Embalm",
  "Exert",
  "Explore",
  "Enrage",
  "Ascend",
  "Jump-start",
  "Mentor",
  "Undergrowth",
  "Convoke",
  "Spectacle",
  "Riot",
  "Amass",
  "Proliferate",
  "Hybrid Mana",

  // Color Identity & Mana
  "Mono-White",
  "Mono-Blue", 
  "Mono-Black",
  "Mono-Red",
  "Mono-Green",
  "Mono-Color Devotion",
  "Color Matters",
  "Multicolor Synergy",
  "WUBRG Matters",
  "Color Hate",
  "Color Identity",
  "Hybrid Synergy",
  "Devotion",
  "Chroma",
  "Sunburst",

  // Format & Multiplayer
  "Commander Specific",
  "Politics",
  "Multiplayer",
  "1v1 Focus",
  "Diplomatic",
  "Kingmaker",
  "Table Politics",
  "Threat Assessment",

  // Win Conditions
  "Alternative Win Cons",
  "Laboratory Maniac",
  "Approach of the Second Sun",
  "Felidar Sovereign",
  "Coalition Victory",
  "Maze's End",
  "Door to Nothingness",
  "Helix Pinnacle",
  "Mayael's Aria",
  "Mortal Combat",
  "Near-Death Experience",
  "Test of Endurance",
  "Chance Encounter",
  "Epic Struggle",
  "Simic Ascendancy",

  // Value & Engine Types
  "Incremental Advantage",
  "Synergy Engines",
  "Value Creatures",
  "Utility Spells",
  "Flexible Answers",
  "Modal Spells",
  "Modular Effects",
  "Scalable Effects",
  "Repeatable Effects",
  "One-Shot Effects",

  // Tribal Categories (Major)
  "Humans",
  "Elves", 
  "Goblins",
  "Merfolk",
  "Zombies",
  "Dragons",
  "Angels",
  "Demons",
  "Spirits",
  "Beasts",
  "Elementals",
  "Slivers",
  "Soldiers",
  "Warriors",
  "Wizards",
  "Knights",
  "Vampires",
  "Werewolves",
  "Pirates",
  "Dinosaurs",
  "Cats",
  "Dogs",
  "Birds",
  "Insects",

  // Major Tribal Strategies
  "Human Tribal",
  "Elf Tribal",
  "Goblin Tribal",
  "Zombie Tribal",
  "Vampire Tribal",
  "Dragon Tribal",
  "Angel Tribal",
  "Demon Tribal",
  "Spirit Tribal",
  "Beast Tribal",
  "Soldier Tribal",
  "Knight Tribal",
  "Wizard Tribal",
  "Warrior Tribal",
  "Rogue Tribal",
  "Cleric Tribal",
  "Shaman Tribal",
  "Druid Tribal",
  "Artificer Tribal",
  "Bird Tribal",
  "Cat Tribal",
  "Dog Tribal",
  "Wolf Tribal",
  "Dinosaur Tribal",
  "Merfolk Tribal",
  "Elemental Tribal",
  "Sliver Tribal",
  "Ally Tribal",

  // Minor Tribal Categories
  "Assassin Tribal",
  "Berserker Tribal",
  "Monk Tribal",
  "Scout Tribal",
  "Spellshaper Tribal",
  "Minion Tribal",
  "Horror Tribal",
  "Nightmare Tribal",
  "Illusion Tribal",
  "Shade Tribal",
  "Wraith Tribal",
  "Specter Tribal",
  "Phoenix Tribal",
  "Griffin Tribal",
  "Pegasus Tribal",
  "Unicorn Tribal",
  "Centaur Tribal",
  "Minotaur Tribal",
  "Satyr Tribal",
  "Nymph Tribal",
  "Treefolk Tribal",
  "Plant Tribal",
  "Fungus Tribal",
  "Ooze Tribal",
  "Slime Tribal",
  "Construct Tribal",
  "Golem Tribal",
  "Gargoyle Tribal",
  "Homunculus Tribal",
  "Thopter Tribal",
  "Myr Tribal",
  "Servo Tribal",
  "Dwarf Tribal",
  "Giant Tribal",
  "Troll Tribal",
  "Ogre Tribal",
  "Orc Tribal",
  "Faerie Tribal",
  "Kithkin Tribal",
  "Halfling Tribal",
  "Kor Tribal",
  "Leonin Tribal",
  "Rhox Tribal",
  "Elephant Tribal",
  "Rhino Tribal",
  "Hippo Tribal",
  "Whale Tribal",
  "Serpent Tribal",
  "Snake Tribal",
  "Lizard Tribal",
  "Crocodile Tribal",
  "Turtle Tribal",
  "Frog Tribal",
  "Fish Tribal",
  "Shark Tribal",
  "Octopus Tribal",
  "Squid Tribal",
  "Crab Tribal",
  "Spider Tribal",
  "Insect Tribal",
  "Ant Tribal",
  "Bee Tribal",
  "Butterfly Tribal",
  "Moth Tribal",
  "Beetle Tribal",
  "Mantis Tribal",
  "Scorpion Tribal",

  // Color Identity & Mana Strategies
  "White Devotion",
  "Blue Devotion",
  "Black Devotion",
  "Red Devotion",
  "Green Devotion",
  "Azorius Strategy",
  "Dimir Strategy",
  "Rakdos Strategy",
  "Gruul Strategy",
  "Selesnya Strategy",
  "Orzhov Strategy",
  "Izzet Strategy",
  "Golgari Strategy",
  "Boros Strategy",
  "Simic Strategy",
  "Esper Strategy",
  "Grixis Strategy",
  "Jund Strategy",
  "Naya Strategy",
  "Bant Strategy",
  "Abzan Strategy",
  "Jeskai Strategy",
  "Sultai Strategy",
  "Mardu Strategy",
  "Temur Strategy",
  "Four Color",
  "Five Color",
  "WUBRG Strategy",
  "Rainbow Mana",
  "Chromatic Strategy",

  // Format Specific Strategies
  "Commander Strategy",
  "EDH Politics",
  "Multiplayer Strategy",
  "1v1 Strategy",
  "Standard Viable",
  "Modern Viable",
  "Legacy Viable",
  "Vintage Viable",
  "Pioneer Viable",
  "Historic Viable",
  "Brawl Strategy",
  "Oathbreaker Strategy",
  "Tiny Leaders",
  "Pauper Strategy",
  "Peasant Strategy",
  "Highlander",
  "Singleton",
  "Limited Strategy",
  "Draft Strategy",
  "Sealed Strategy",

  // Interaction Types & Game Theory
  "Reactive Strategy",
  "Proactive Strategy",
  "Permission Strategy",
  "Disruption Strategy",
  "Control Elements",
  "Aggressive Elements",
  "Defensive Elements",
  "Symmetrical Effects",
  "Asymmetrical Advantage",
  "Targeted Effects",
  "Non-Targeted Effects",
  "Conditional Effects",
  "Unconditional Effects",
  "Political Strategy",
  "Group Strategy",
  "Alliance Strategy",
  "Threat Assessment",
  "Table Politics",
  "Kingmaking",
  "Spite Strategy",
  "Revenge Strategy",
  "Diplomatic Strategy",

  // Deck Construction & Meta
  "Toolbox Strategy",
  "Silver Bullets",
  "Hate Bears",
  "Hate Cards",
  "Sideboard Strategy",
  "Wishboard",
  "Learn Strategy",
  "Lesson Strategy",
  "Modal Cards",
  "Flexible Cards",
  "Multi-Purpose",
  "Value Engine",
  "Card Advantage Engine",
  "Mana Engine",
  "Combo Engine",
  "Win Condition",
  "Alternate Win",
  "Laboratory Maniac",
  "Thassa's Oracle",
  "Approach Win",
  "Combat Win",
  "Damage Win",
  "Mill Win",
  "Poison Win",
  "Infect Win",
  "Commander Damage",
  "Voltron Win",

  // Special Categories & Archetypes
  "Surprise Factor",
  "Unexpected Strategy",
  "Meme Strategy",
  "Jank Strategy",
  "Jank Combo",
  "Kitchen Table",
  "Casual Strategy",
  "Competitive Strategy",
  "Budget Strategy",
  "Expensive Strategy",
  "High Budget",
  "Low Budget",
  "Linear Strategy",
  "Nonlinear Strategy",
  "All-In Strategy",
  "Backup Plan",
  "Plan B Strategy",
  "Flexible Gameplan",
  "Resilient Strategy",
  "Glass Cannon",
  "High Risk High Reward",
  "Consistent Strategy",
  "Explosive Potential",
  "Slow Strategy",
  "Fast Strategy",
  "Midrange Pace",
  "Variable Pace",
  "Adaptive Strategy",
  "Meta Strategy",
  "Anti-Meta",
  "Hate Strategy",
  "Prison Strategy",
  "Lock Strategy",
  "Denial Strategy",
  "Permission Strategy",
  "Draw-Go",
  "Tap-Out",
  "Flash Strategy",
  "Instant Speed",
  "Sorcery Speed",
  "Main Phase",
  "End Step",
  "Upkeep Strategy",
  "Combat Strategy",
  "Stack Strategy",
  "Priority Strategy",
  "Response Strategy",
] as const;

export type PredefinedTheme = typeof PREDEFINED_THEMES[number];

// Helper function to validate if a theme is predefined
export function isValidTheme(theme: string): theme is PredefinedTheme {
  return PREDEFINED_THEMES.includes(theme as PredefinedTheme);
}

// Helper function to get closest matching theme (for AI fallback)
export function getClosestTheme(input: string): PredefinedTheme {
  const inputLower = input.toLowerCase();
  
  // Direct match
  const directMatch = PREDEFINED_THEMES.find(theme => 
    theme.toLowerCase() === inputLower
  );
  if (directMatch) return directMatch;
  
  // Partial match
  const partialMatch = PREDEFINED_THEMES.find(theme => 
    theme.toLowerCase().includes(inputLower) || 
    inputLower.includes(theme.toLowerCase())
  );
  if (partialMatch) return partialMatch;
  
  // Keyword matching
  const keywords: Record<string, PredefinedTheme[]> = {
    'creature': ['Tribal', 'Go-Wide', 'Big Creatures'],
    'spell': ['Spellslinger', 'Storm', 'Instant Speed'],
    'artifact': ['Artifacts Matter', 'Equipment', 'Artifact Ramp'],
    'graveyard': ['Graveyard Recursion', 'Reanimator', 'Self-Mill'],
    'counter': ['+1/+1 Counters', 'Proliferate', 'Counter Manipulation'],
    'life': ['Lifegain', 'Drain Strategy', 'Lifegain Matters'],
    'land': ['Landfall', 'Ramp', 'Lands Matter'],
    'draw': ['Card Advantage', 'Draw Engines', 'Cantrips'],
    'token': ['Tokens', 'Go-Wide', 'Aristocrats'],
    'damage': ['Burn', 'Direct Damage', 'Aggro'],
  };
  
  for (const [keyword, themes] of Object.entries(keywords)) {
    if (inputLower.includes(keyword)) {
      return themes[0];
    }
  }
  
  // Default fallback
  return 'Midrange';
}