// Comprehensive list of Magic: The Gathering strategic themes
// AI must choose only from these predefined categories

export const PREDEFINED_THEMES = [
  // Core Archetypes
  "Aggro",
  "Control",
  "Midrange",
  "Combo",
  "Tempo",
  "Prison",
  "Stax",
  "Hatebears",
  "Burn",
  "Mill",
  "Voltron",
  "Group Slug",
  "Group Hug",
  "Pillow Fort",
  "Chaos",
  "Tax Effects",
  "Resource Denial",
  "Asymmetric Effects",

  // Resource Management
  "Card Advantage",
  "Ramp",
  "Mana Dorks",
  "Land Destruction",
  "Hand Disruption",
  "Draw Engines",
  "Cantrips",
  "Card Selection",
  "Tutoring",
  "Library Manipulation",
  "Deck Thinning",
  "Card Velocity",
  "Selection Effects",
  "Information Advantage",
  "Resource Conversion",

  // Creature Strategies
  "Tribal",
  "Go-Wide",
  "Tokens",
  "Aristocrats",
  "Sacrifice Synergy",
  "Reanimator",
  "Graveyard Value",
  "Graveyard Hate",
  "Big Creatures",
  "Creature Cheating",
  "ETB Value",
  "LTB Value",
  "Blink/Flicker",
  "Creature Toolbox",
  "Hatching",
  "Creature Tutors",
  "Creature Recursion",
  "Clone Effects",
  "Polymorph Effects",
  "Mass Creature Effects",

  // Combat & Damage
  "Combat Tricks",
  "Pump Spells",
  "Evasion",
  "Double Strike",
  "Trample",
  "Flying Matters",
  "Unblockable",
  "Direct Damage",
  "Lifegain",
  "Lifelink Matters",
  "Lifegain Matters",
  "Drain Strategy",
  "Life Total Matters",
  "Damage Redirection",
  "Combat Control",
  "Alpha Strike",
  "Pingers",
  "Deathtouch Matters",
  "First Strike Matters",
  "Vigilance Matters",

  // Spell-Based Strategies
  "Spellslinger",
  "Storm",
  "Cascade",
  "Cascade/Cheating",
  "Cost Reduction",
  "X-Spells",
  "Instant Speed",
  "Flash",
  "Counterspells",
  "Removal",
  "Board Wipes",
  "Spot Removal",
  "Copy Spells",
  "Spell Recursion",
  "Big Spells",
  "Ritual Effects",
  "Spell Velocity",
  "Spell Matters",
  "Magecraft",
  "Prowess",

  // Artifact Strategies
  "Artifacts Matter",
  "Equipment",
  "Equipment Voltron",
  "Artifact Ramp",
  "Artifact Combo",
  "Metalcraft",
  "Affinity",
  "Modular",
  "Artifact Tokens",
  "Artifact Sacrifice",
  "Artifact Recursion",
  "Treasure",
  "Food",
  "Clue",
  "Blood",
  "Powerstone",
  "Myr Tribal",
  "Construct Tribal",
  "Thopter Synergy",
  "Servo Synergy",

  // Enchantment Strategies
  "Enchantments Matter",
  "Auras",
  "Aura Voltron",
  "Enchantress",
  "Constellation",
  "Curse Strategy",
  "Enchantment Recursion",
  "Saga Synergy",
  "Global Enchantments",
  "Enchantment Tokens",

  // Land Strategies
  "Landfall",
  "Lands Matter",
  "Land Ramp",
  "Land Sacrifice",
  "Utility Lands",
  "Multicolor Fixing",
  "Land Animation",
  "Land Tutors",
  "Basic Lands Matter",
  "Nonbasic Hate",
  "Domain",
  "Converge",
  "Gate Synergy",
  "Desert Synergy",

  // Graveyard Strategies
  "Graveyard Recursion",
  "Self-Mill",
  "Dredge",
  "Delve",
  "Flashback",
  "Threshold",
  "Delirium",
  "Escape",
  "Embalm",
  "Eternalize",
  "Unearth",
  "Retrace",
  "Disturb",
  "Graveyard as Resource",
  "Fill Graveyard",
  "Graveyard Order",

  // Counter & Token Strategies
  "+1/+1 Counters",
  "Proliferate",
  "Counter Manipulation",
  "Planeswalker Support",
  "Energy",
  "Experience Counters",
  "Loyalty Counters",
  "Charge Counters",
  "Storage Counters",
  "Time Counters",
  "Poison Counters",
  "Infect",
  "Undying",
  "Persist",
  "Evolve",
  "Adapt",
  "Monstrosity",

  // Timing & Phase Strategies
  "End Step Matters",
  "Upkeep Triggers",
  "Beginning of Combat",
  "Extra Turns",
  "Extra Combat",
  "Instant Speed Value",
  "Split Second",
  "Stack Interaction",
  "Triggered Abilities",
  "Activated Abilities",
  "Static Abilities",

  // Protection & Resilience
  "Protection",
  "Hexproof/Shroud",
  "Indestructible",
  "Regeneration",
  "Bounce Effects",
  "Phasing",
  "Ward",
  "Totem Armor",
  "Shield Counters",
  "Damage Prevention",
  "Redirection",

  // Specific Mechanics (A-M)
  "Cycling",
  "Madness",
  "Morph",
  "Suspend",
  "Kicker",
  "Overload",
  "Convoke",
  "Emerge",
  "Mutate",
  "Adventure",
  "Foretell",
  "Miracle",
  "Buyback",
  "Echo",
  "Entwine",
  "Fading",
  "Vanishing",
  "Forecast",
  "Graft",
  "Haunt",
  "Hideaway",
  "Kinship",
  "Ninjutsu",
  "Offering",
  "Reinforce",
  "Ripple",
  "Splice",
  "Transmute",
  "Amplify",
  "Bloodthirst",
  "Clash",
  "Conspire",
  "Devour",
  "Exalted",
  "Landfall",
  "Level Up",
  "Multikicker",

  // Specific Mechanics (N-Z)
  "Annihilator",
  "Battle Cry",
  "Living Weapon",
  "Phyrexian Mana",
  "Soulbond",
  "Undying",
  "Cipher",
  "Evolve",
  "Extort",
  "Fuse",
  "Scavenge",
  "Unleash",
  "Bestow",
  "Heroic",
  "Inspired",
  "Strive",
  "Tribute",
  "Dash",
  "Exploit",
  "Formidable",
  "Megamorph",
  "Prowess",
  "Rebound",
  "Surge",
  "Awaken",
  "Ingest",
  "Devoid",
  "Colorless Matters",
  "Crew",
  "Fabricate",
  "Partner",
  "Improvise",
  "Revolt",
  "Aftermath",
  "Embalm",
  "Exert",
  "Explore",
  "Enrage",
  "Ascend",
  "Jump-start",
  "Mentor",
  "Undergrowth",
  "Convoke",
  "Spectacle",
  "Riot",
  "Amass",
  "Proliferate",
  "Hybrid Mana",

  // Color Identity & Mana
  "Mono-White",
  "Mono-Blue", 
  "Mono-Black",
  "Mono-Red",
  "Mono-Green",
  "Mono-Color Devotion",
  "Color Matters",
  "Multicolor Synergy",
  "WUBRG Matters",
  "Color Hate",
  "Color Identity",
  "Hybrid Synergy",
  "Devotion",
  "Chroma",
  "Sunburst",

  // Format & Multiplayer
  "Commander Specific",
  "Politics",
  "Multiplayer",
  "1v1 Focus",
  "Diplomatic",
  "Kingmaker",
  "Table Politics",
  "Threat Assessment",

  // Win Conditions
  "Alternative Win Cons",
  "Laboratory Maniac",
  "Approach of the Second Sun",
  "Felidar Sovereign",
  "Coalition Victory",
  "Maze's End",
  "Door to Nothingness",
  "Helix Pinnacle",
  "Mayael's Aria",
  "Mortal Combat",
  "Near-Death Experience",
  "Test of Endurance",
  "Chance Encounter",
  "Epic Struggle",
  "Simic Ascendancy",

  // Value & Engine Types
  "Incremental Advantage",
  "Synergy Engines",
  "Value Creatures",
  "Utility Spells",
  "Flexible Answers",
  "Modal Spells",
  "Modular Effects",
  "Scalable Effects",
  "Repeatable Effects",
  "One-Shot Effects",

  // Tribal Categories (Major)
  "Humans",
  "Elves", 
  "Goblins",
  "Merfolk",
  "Zombies",
  "Dragons",
  "Angels",
  "Demons",
  "Spirits",
  "Beasts",
  "Elementals",
  "Slivers",
  "Soldiers",
  "Warriors",
  "Wizards",
  "Knights",
  "Vampires",
  "Werewolves",
  "Pirates",
  "Dinosaurs",
  "Cats",
  "Dogs",
  "Birds",
  "Insects",

  // Tribal Categories (Minor)
  "Clerics",
  "Rogues",
  "Shamans",
  "Druids",
  "Artificers",
  "Assassins",
  "Berserkers",
  "Monks",
  "Scouts",
  "Spellshapers",
  "Minions",
  "Horrors",
  "Nightmares",
  "Illusions",
  "Shades",
  "Wraiths",
  "Specters",
  "Phoenixes",
  "Griffins",
  "Pegasus",
  "Unicorns",
  "Centaurs",
  "Minotaurs",
  "Satyrs",
  "Nymphs",
  "Treefolk",
  "Plants",
  "Fungi",
  "Oozes",
  "Slimes",
  "Constructs",
  "Golems",
  "Gargoyles",
  "Homunculus",
  "Thopters",
  "Myr",
  "Servo",

  // Interaction Types
  "Reactive Strategy",
  "Proactive Strategy",
  "Permission",
  "Disruption",
  "Symmetrical Effects",
  "Asymmetrical Advantage",
  "Targeted Removal",
  "Mass Removal",
  "Conditional Effects",
  "Unconditional Effects",

  // Special Categories
  "Surprise Factor",
  "Meme Strategy",
  "Jank Combo",
  "Kitchen Table",
  "Casual Friendly",
  "Competitive Viable",
  "Budget Friendly",
  "Expensive to Build",
  "Linear Strategy",
  "Nonlinear Strategy",
  "All-In Strategy",
  "Backup Plan",
  "Plan B",
  "Flexible Gameplan",
  "Resilient Strategy",
  "Glass Cannon",
  "Consistent Strategy",
  "Explosive Potential",
] as const;

export type PredefinedTheme = typeof PREDEFINED_THEMES[number];

// Helper function to validate if a theme is predefined
export function isValidTheme(theme: string): theme is PredefinedTheme {
  return PREDEFINED_THEMES.includes(theme as PredefinedTheme);
}

// Helper function to get closest matching theme (for AI fallback)
export function getClosestTheme(input: string): PredefinedTheme {
  const inputLower = input.toLowerCase();
  
  // Direct match
  const directMatch = PREDEFINED_THEMES.find(theme => 
    theme.toLowerCase() === inputLower
  );
  if (directMatch) return directMatch;
  
  // Partial match
  const partialMatch = PREDEFINED_THEMES.find(theme => 
    theme.toLowerCase().includes(inputLower) || 
    inputLower.includes(theme.toLowerCase())
  );
  if (partialMatch) return partialMatch;
  
  // Keyword matching
  const keywords: Record<string, PredefinedTheme[]> = {
    'creature': ['Tribal', 'Go-Wide', 'Big Creatures'],
    'spell': ['Spellslinger', 'Storm', 'Instant Speed'],
    'artifact': ['Artifacts Matter', 'Equipment', 'Artifact Ramp'],
    'graveyard': ['Graveyard Recursion', 'Reanimator', 'Self-Mill'],
    'counter': ['+1/+1 Counters', 'Proliferate', 'Counter Manipulation'],
    'life': ['Lifegain', 'Drain Strategy', 'Lifegain Matters'],
    'land': ['Landfall', 'Ramp', 'Lands Matter'],
    'draw': ['Card Advantage', 'Draw Engines', 'Cantrips'],
    'token': ['Tokens', 'Go-Wide', 'Aristocrats'],
    'damage': ['Burn', 'Direct Damage', 'Aggro'],
  };
  
  for (const [keyword, themes] of Object.entries(keywords)) {
    if (inputLower.includes(keyword)) {
      return themes[0];
    }
  }
  
  // Default fallback
  return 'Midrange';
}