// Core Magic: The Gathering strategy themes for card categorization
// Total: ~200 essential strategic categories covering major archetypes

export const PREDEFINED_THEMES = [
  // Core Archetypes (15 themes)
  "Aggro",
  "Control", 
  "Midrange",
  "Combo",
  "Ramp",
  "Tempo",
  "Prison",
  "Stax",
  "Burn",
  "Mill",
  "Reanimator",
  "Cheating",
  "Voltron",
  "Tribal",
  "Toolbox",

  // Mana & Resources (20 themes)
  "Mana Acceleration",
  "Mana Fixing",
  "Mana Denial",
  "Land Destruction",
  "Resource Denial",
  "Card Advantage",
  "Card Selection",
  "Hand Disruption",
  "Library Manipulation",
  "Graveyard Value",
  "Exile Matters",
  "Treasure",
  "Scry",
  "Surveil",
  "Impulse Draw",
  "Cascade",
  "Storm",
  "Dredge",
  "Cycling",
  "Madness",

  // Creature Strategies (25 themes)
  "Go-Wide",
  "Go-Tall",
  "Tokens",
  "Aristocrats",
  "Sacrifice Synergy",
  "Death Triggers",
  "ETB Effects",
  "LTB Effects",
  "Creature Tutors",
  "Creature Protection",
  "Equipment",
  "Auras",
  "Pump Effects",
  "Combat Tricks",
  "Double Strike",
  "First Strike",
  "Trample",
  "Flying",
  "Vigilance",
  "Haste",
  "Hexproof",
  "Shroud",
  "Ward",
  "Indestructible",
  "Regeneration",

  // Tribal Themes (20 themes)
  "Angel Tribal",
  "Beast Tribal", 
  "Bird Tribal",
  "Cat Tribal",
  "Demon Tribal",
  "Dragon Tribal",
  "Elf Tribal",
  "Goblin Tribal",
  "Human Tribal",
  "Knight Tribal",
  "Merfolk Tribal",
  "Soldier Tribal",
  "Spirit Tribal",
  "Vampire Tribal",
  "Wizard Tribal",
  "Zombie Tribal",
  "Artifact Creatures",
  "Changeling",
  "Shapeshifter",
  "Tribal Support",

  // Artifact Strategies (15 themes)
  "Artifact Synergy",
  "Artifact Tokens",
  "Artifact Sacrifice",
  "Artifact Ramp",
  "Artifact Combo",
  "Improvise",
  "Affinity",
  "Metalcraft",
  "Modular",
  "Equipment Matters",
  "Vehicle Tribal",
  "Construct Tribal",
  "Golem Tribal",
  "Thopter Tribal",
  "Servo Tribal",

  // Enchantment Strategies (10 themes)
  "Enchantment Synergy",
  "Aura Synergy",
  "Constellation",
  "Enchantress",
  "Curse Tribal",
  "Saga Tribal",
  "Shrine Tribal",
  "Enchantment Ramp",
  "Enchantment Protection",
  "Enchantment Removal",

  // Graveyard Strategies (15 themes)
  "Reanimation Strategy",
  "Self-Mill",
  "Flashback",
  "Delve",
  "Escape",
  "Threshold",
  "Delirium",
  "Undergrowth",
  "Graveyard Hate",
  "Graveyard Removal",
  "Recursion",
  "Graveyard Tutors",
  "Laboratory Maniac",
  "Jace Victory",
  "Thassa's Oracle",

  // Counter Strategies (10 themes)
  "+1/+1 Counters",
  "-1/-1 Counters",
  "Charge Counters",
  "Energy Counters",
  "Loyalty Counters",
  "Experience Counters",
  "Proliferate",
  "Counter Removal",
  "Counter Doubling",
  "Modular Synergy",

  // Spell Strategies (15 themes)
  "Instant Speed",
  "Sorcery Speed",
  "Flash",
  "Split Second",
  "Uncounterable",
  "Copy Spells",
  "Fork Effects",
  "Spell Slinger",
  "Cantrips",
  "X Spells",
  "Modal Spells",
  "Adventure",
  "Kicker",
  "Overload",
  "Suspend",

  // Protection & Control (15 themes)
  "Counterspells",
  "Removal",
  "Board Wipes",
  "Spot Removal",
  "Mass Removal",
  "Protection Spells",
  "Blink Effects",
  "Flicker Effects",
  "Bounce Effects",
  "Tax Effects",
  "Hatebears",
  "Permission",
  "Disruption",
  "Interaction",
  "Response Package",

  // Win Conditions (15 themes)
  "Alternate Win Cons",
  "Combat Damage",
  "Direct Damage",
  "Life Loss",
  "Life Drain",
  "Mill Win",
  "Poison",
  "Infect",
  "Commander Damage",
  "Planeswalker Ultimate",
  "Combo Win",
  "Lock Win",
  "Value Win",
  "Attrition Win",
  "Overwhelming Board",

  // Multiplayer & Politics (10 themes)
  "Group Hug",
  "Group Slug",
  "Pillow Fort",
  "Politics",
  "Kingmaker",
  "Threat Assessment",
  "Table Balance",
  "Ally Effects",
  "Global Effects",
  "Symmetrical Effects"
];

// Theme count validation: 200 essential Magic strategy categories